### ISSUE TITLE
AB/n 

### ISSUE THREAD

**Issue by glilienthal** [WeMoveEU/splitest#1]
IMHO, you should for all test always make them AB/n-tests, i.e., one should not only be able to test A:B, but A:B:C:D:E:F:G.... 

I wouldn't insist if it was an amazing extra work, but I can imagine it is important to keep that in mind even at the beginning.

**Comment by tttp** [comment]
it's the aim to be able to do abn, is there anywhere in the code it's not the case?

**Comment by scardinius** [comment]
AlephBet support multiple variants

**Comment by glilienthal** [comment]
So maybe you should write ABn everywhere.

**Comment by tttp** [comment]
done everywhere (I think)
